// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Dog struct {
	ID        string `json:"_id"`
	Name      string `json:"name"`
	IsGoodboi bool   `json:"isGoodboi"`
}

type NewDog struct {
	Name      string `json:"name"`
	IsGoodboi bool   `json:"isGoodboi"`
}
